controller_list:
  - name: fake_right_arm_controller
    joints:
      - arm_2_joint_1
      - arm_2_joint_2
      - arm_2_joint_3
      - arm_2_joint_4
      - arm_2_joint_5
  - name: fake_left_arm_controller
    joints:
      - arm_1_joint_1
      - arm_1_joint_2
      - arm_1_joint_3
      - arm_1_joint_4
      - arm_1_joint_5
  - name: fake_right_gripper_controller
    joints:
      - arm_2_finger_left_joint
  - name: fake_left_gripper_controller
    joints:
      - arm_1_finger_left_joint